name: go e2e test
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/go.test.e2e.yaml
      - "**/*.go"
      - go.mod
      - go.sum
jobs:
  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go mod tidy
        run: go mod tidy
      - name: Run app
        id: run-app
        run: |
          go run cmd/app/main.go &
          echo pid=$! >> $GITHUB_OUTPUT
          sleep 20
      - name: Go test e2e
        env:
          E2E_ENDPOINT: http://localhost:8080
        run: go test ./test/e2e/... -tags e2e
      - name: Shutdown
        if: always()
        run: kill ${{ steps.run-app.outputs.pid }}
